### ISSUE TITLE
Feature: Named Work Values & Flags

### ISSUE THREAD

**Issue by z80rotom** [SaltContainer/PokemonBDSPEditor#1]
It would be nice to have names for the work values and flags accepted by the editor rather than having to remember that var_246 is SCWK_ANSWER. Feel free to refer to https://github.com/z80rotom/ev-as/blob/main/src/ev_flag.py for flag names. It is also convenient to be able to define new work & flag values names for new scripts if you're doing sufficiently large story edits.

**Comment by SaltContainer** [comment]
Ah, I wasn't aware that there were defined names for flags and work values! That is very nice to know.
I'll work on adding those soon.

For defining new ones, that might take longer to set up, but that should be doable without much issue; I have some ideas for how to implement it.

Thank you for this info!

**Comment by SaltContainer** [comment]
Implemented with #2. Will be making a 1.2.0 release in a moment.
